### ISSUE TITLE
Uncaught TypeError: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by ryun** [igogo5yo/atom-php-navigation#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-php-navigation](https://github.com/igogo5yo/atom-php-navigation) package, v0.5.0
### Stack Trace

Uncaught TypeError: Cannot read property 'end' of undefined

```
At /Users/ryan/.atom/packages/atom-php-navigation/lib/atom-php-navigation.coffee:93

TypeError: Cannot read property 'end' of undefined
  at Object.module.exports.AtomPhpNavigation.createMarker (/Users/ryan/.atom/packages/atom-php-navigation/lib/atom-php-navigation.coffee:93:28)
  at /Users/ryan/.atom/packages/atom-php-navigation/lib/atom-php-navigation.coffee:170:27
  at /Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:731:18
  at TextBuffer.module.exports.TextBuffer.scanInRange (/Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:785:9)
  at TextBuffer.module.exports.TextBuffer.scan (/Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:727:19)
  at TextEditor.module.exports.TextEditor.scan (/Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/src/text-editor.js:2227:26)
  at Object.module.exports.AtomPhpNavigation.scanExtends (/Users/ryan/.atom/packages/atom-php-navigation/lib/atom-php-navigation.coffee:159:12)
  at /Users/ryan/.atom/packages/atom-php-navigation/lib/atom-php-navigation.coffee:68:8
  at Workspace.module.exports.Workspace.observeTextEditors (/Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/src/workspace.js:272:9)
  at Object.module.exports.AtomPhpNavigation.enable (/Users/ryan/.atom/packages/atom-php-navigation/lib/atom-php-navigation.coffee:63:46)
  at Object.module.exports.AtomPhpNavigation.toggle (/Users/ryan/.atom/packages/atom-php-navigation/lib/atom-php-navigation.coffee:54:8)
  at atom-workspace.subscriptions.add.atom.commands.add.atom-php-navigation:toggle (/Users/ryan/.atom/packages/atom-php-navigation/lib/atom-php-navigation.coffee:38:94)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/ryan/Documents/_Imported/Apps/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```
### Commands

```
     -8:50.9 application:quit (atom-text-editor#atom-pair.hipchat_token.editor.mini)
     -7:49.1 core:save (atom-text-editor#atom-pair.hipchat_token.editor.mini)
     -7:09.5 core:confirm (atom-text-editor.editor.mini)
     -0:33.1 editor:toggle-line-comments (atom-text-editor.editor)
     -0:26.8 tree-view:toggle (atom-text-editor.editor)
     -0:00.7 atom-php-navigation:toggle (atom-text-editor#AtomPair.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
atom-pair, v2.0.3
atom-php-navigation, v0.5.0
autocomplete-php, v0.3.6
php-getters-setters, v0.5.5
seti-syntax, v0.4.0

# Dev
No dev packages
```

**Comment by igogo5yo** [comment]
Can you try this with new version?
